name: Build aria2

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake autopoint autotools-dev libxml2-dev libcppunit-dev libtool libffi-dev libgnutls28-dev nettle-dev libgmp-dev libssh2-1-dev libc-ares-dev zlib1g-dev libsqlite3-dev pkg-config make quilt checkinstall
          wget https://dl.google.com/android/repository/android-ndk-r27-linux.zip
          unzip -q android-ndk-r27-linux.zip
          export ANDROID_NDK_HOME=`pwd`/android-ndk-r27
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export SILENT=true
      - name: Build
        run: |
          ./build_all.sh
          mv ./bin/armeabi-v7a/bin/aria2c ./bin/armeabi-v7a/bin/libaria2c.so
          mv ./bin/arm64-v8a/bin/aria2c ./bin/arm64-v8a/bin/libaria2c.so
          mv ./bin/x86/bin/aria2c ./bin/x86/bin/libaria2c.so
          mv ./bin/x86_64/bin/aria2c ./bin/x86_64/bin/libaria2c.so

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: aria2c
          path: './bin/**/bin/libaria2c.so'
